name: "🤖 Daily update"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  new-update:
    name: New update
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: "Prepare env"
        run: |
          echo ${{ secrets.KEYSTORE_B64 }} | base64 -d | zcat >> keystore.p12
          echo ${{ secrets.CONFIG_B64 }} | base64 -d | zcat >> config.yml
      - name: "Update repo"
        run: |
          pip install -r update_apks.requirements.txt
          python update_apks.py
      - name: "Check if any changes"
        id: check-changes
        run: |
          has_changes=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
          echo "$has_changes"
          echo "HAS_CHANGES=$has_changes" >> "$GITHUB_OUTPUT"
      - name: "Commit and push changes"
        if: ${{ startsWith(steps.check-changes.outputs.HAS_CHANGES, 'true') }}
        run: |
          git config user.email github-actions@github.com
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Mirror latest Keyguard artifact from GitHub Releases"
          git push origin master
